CSRF_ENABLED = True
SECRET_KEY = 'OwYM8Lqy3mnRw9rvj6ca6Xo10UAS2F8a'

SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
#SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:root@127.0.0.1:3306/SWE573'
SQLALCHEMY_TRACK_MODIFICATIONS = True